project:
  type: book
  output-dir: docs


website:
  title: "NES2504 Professional Skills: Data Analysis Handbook"
  site-url: https://rasanderson.github.io/NES2504-ModuleHandbook/


book:
  title: "NES2504 Data Analysis Handbook"
  reader-mode: true
  
  page-footer:
    left: |
      NES2504 Data Analysis Handbook. 2025-26 Edition. Roy Sanderson, Will Reid.
    right: |
      This handbook was built with <a href="https://quarto.org/">Quarto</a>.

  cover-image: cover.png
  favicon: cover.png
  site-url: https://ncl.instructure.com/courses/72463
  repo-url: https://github.com/rasanderson/NES2504-ModuleHandbook
  repo-branch: main
  repo-actions: [edit, issue]

  author: "Roy Sanderson, Will Reid"
  date: "25/08/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - biomod.qmd
    - goals.qmd
    - signal_noise.qmd
    - structure.qmd
    - weekly.qmd
    - assessments.qmd
    - software.qmd
    - stage3.qmd
    - reports.qmd
    - final_remarks.qmd
    
format:
  html:
    theme:
      - cosmo
      - custom.scss
      - brand
    code-link: true
  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
    filters: [boxed-span.lua]
    include-in-header: preamble.tex
    include-before: |
      \thispagestyle{empty}
      \begin{center}
      \includegraphics[width=\textwidth]{cover.png}
      \end{center}
      \newpage
  


editor: source

