# Welcome {.unnumbered}

This is the 2026-27 edition of the Data Analysis Handbook for NES2504 Professional Skills. The handbook contains information about the module, including its aims, learning outcomes, assessment details, and schedule. You can access it via either the HTML or PDF format. If using the HTML format, you can navigate through the handbook using the sidebar on the left. The PDF version is available for download [here](https://rasanderson.github.io/NES2504-AnalysisHandbook/NES2504-Data-Analysis-Handbook.pdf){target="_blank"}.

We recognise that as Biology, Zoology, Marine Biology or Marine Zoology undergraduates, you may not have a strong background in statistics. Therefore, we have designed the module to be accessible to all students, regardless of their prior knowledge. This Data Analysis course will provide you with the necessary statistical skills to design and analyse experiments effectively. Each week you will be expected to undertake a small amount of reading, view a short video and use an interactive website to ensure you understand the concepts. The module will also include practical sessions where you will apply the statistical techniques learned in lectures to real data sets.

## Pre-requisites
Most of you will not have done A-levels or Scottish Highers in Mathematics or Statistics, and are probably uninterested in the subject. We've therefore designed the module to be accessible to all students, regardless of their prior knowledge. The module will provide you with the necessary statistical skills to design and analyse experiments effectively. The only key pre-requisite is that you know how to calculate an average (mean)!

## Module codes
Over the last 3 years the module code has changed three times. You may therefore find some material referencing BIO2020, NES2303 or NES2504. Apologies for the confusion.