```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

This document provides you with the aims and rationale behind the course, explains its mode of delivery, staff roles, and forms of assessment. More importantly, it explains the underlying philosophy used to teach experimental design and statistics, which will probably differ from most that you may have previously encountered, or seen in textbooks. A common approach is to provide students with a plethora of different statistical tests that they may or may not need to apply to their data, depending on how they collected their data, the aims and objectives of their experiment etc. This can be very confusing, resulting in bafflement (that was our experience as undergraduates) with the result that some UG textbooks provide complex flowcharts to help students select the appropriate test.

A second challenge is the type of software used to undertake statistics. We are just old enough to remember doing some basic statistical tests with a calculator which would take a whole afternoon, even with a relatively small sample size. The arrival of computers to take the tedium out of this was a great relief. Most software commonly used for statistics, such as Microsoft Excel, Minitab and SPSS are menu-driven, making it easy to get started with data analysis and graph display. However, whilst their learning curve is initially very shallow, it soon becomes steep. Biological data is inherently complex, and often the more advanced analyses or data visualisations are difficult or impossible to undertake. An additional problem is that you have no record of what you have done. You will be taking this course in October to December of your Stage 2, but many of the skills you will learn will not be practiced in full until you are doing Stage 3 courses and projects. If you do not need to do much statistics after completing this NES2504 course, will you remember what you need in 18 months' time for your Final Year Project or other experiments/surveys? If you have menu-driven software, it is easy to learn, but easy to forget. In contrast, we will use a coding language that is now common in Biology, Zoology and Marine Science, called R. It is (slightly) harder to learn than menu-driven software, but you don't forget it, even 12 months later! Many careers in biology and zoology, both laboratory and field-based, expect applicants to know how to use R. We have therefore developed this course to give you the best employability skills for your CV as well.

Finally, this is the third year in which we have taught on this course and it is updated each year to try and improve it based on your feedback. There is an initial "Session 0" revision computer class to help you configure and 'navigate' the software we'll use. This will hopefully ensure that in the subsequent practicals you can focus on data science for biologists and zoologists, and not worry about IT. Passive learning in lectures is not particularly useful for quantitative biologists and zoologists like yourselves, and hands-on experience is more useful, so additional practicals are always valuable. You can start practicals in your own time if you wish. If you find yourself making excellent progress, do not feel obliged to attend every practical; however repeating some exercises will embed your knowledge. Also **understanding** is key: getting the 'right' answer from an analysis is **not** sufficient. You need to know how to interpret its biological meaning.

Please provide feedback (positive or negative) as you progress through the Data Analysis course either directly to Roy Sanderson and Will Reid, or to your student representatives for the Marine Biology, Marine Zoology, Biology and Zoology degree programmes.

